{
    "openapi": "3.0.1",
    "info": {
        "title": "Emails",
        "description": "CRM objects such as companies, contacts, deals, line items, products, tickets, and quotes are standard objects in HubSpot's CRM. These core building blocks support custom properties, store critical information, and play a central role in the HubSpot application.\n\n## Supported Object Types\n\nThis API provides access to collections of CRM objects, which return a map of property names to values. Each object type has its own set of default properties, which can be found by[...]",
        "version": "v3",
        "x-hubspot-product-tier-requirements": {
            "marketing": "FREE",
            "sales": "FREE",
            "service": "FREE",
            "cms": "FREE",
            "commerce": "FREE",
            "crmHub": "FREE",
            "dataHub": "FREE"
        },
        "x-hubspot-api-use-case": "You send and manage emails to your customers using a third-party email provider, and you want to programmatically log your email data to the associated records in your HubSpot account.",
        "x-hubspot-related-documentation": [
            {
                "name": "Emails Guide",
                "url": "https://developers.hubspot.com/docs/guides/api/crm/engagements/email"
            }
        ],
        "x-hubspot-introduction": "Use the email engagements API to associate emails with records in your CRM. You can include various metadata fields as needed, including the email's headers, subject line, and body."
    },
    "servers": [
        {
            "url": "https://api.hubapi.com/crm/v3/objects/emails"
        }
    ],
    "tags": [
        {
            "name": "Basic"
        },
        {
            "name": "Batch"
        },
        {
            "name": "Search"
        }
    ],
    "paths": {
        "": {
            "get": {
                "tags": [
                    "Basic"
                ],
                "summary": "List",
                "description": "Read a page of emails. Control what is returned via the `properties` query param.",
                "operationId": "get-/crm/v3/objects/emails_getPage",
                "security": [
                    {
                        "oauth2": [
                            "crm.objects.contacts.read",
                            "sales-email-read"
                        ]
                    }
                ]
            },
            "post": {
                "tags": [
                    "Basic"
                ],
                "summary": "Create",
                "description": "Create a email with the given properties and return a copy of the object, including the ID. Documentation and examples for creating standard emails is provided.",
                "operationId": "post-/crm/v3/objects/emails_create",
                "security": [
                    {
                        "oauth2": [
                            "crm.objects.contacts.write",
                            "sales-email-read"
                        ]
                    }
                ]
            }
        },
        "/batch/archive": {
            "post": {
                "tags": [
                    "Batch"
                ],
                "summary": "Archive a batch of emails by ID",
                "description": "Archive a batch of emails identified by their IDs.",
                "operationId": "post-/crm/v3/objects/emails/batch/archive_archive",
                "security": [
                    {
                        "oauth2": [
                            "crm.objects.contacts.write",
                            "sales-email-read"
                        ]
                    }
                ]
            }
        },
        "/batch/create": {
            "post": {
                "tags": [
                    "Batch"
                ],
                "summary": "Create a batch of emails",
                "description": "Create a batch of emails with specified properties and return the created objects.",
                "operationId": "post-/crm/v3/objects/emails/batch/create_create",
                "security": [
                    {
                        "oauth2": [
                            "crm.objects.contacts.write",
                            "sales-email-read"
                        ]
                    }
                ]
            }
        },
        "/batch/read": {
            "post": {
                "tags": [
                    "Batch"
                ],
                "summary": "Read a batch of emails by internal ID, or unique property values",
                "description": "Retrieve records by record ID or include the `idProperty` parameter to retrieve records by a custom unique value property. ",
                "operationId": "post-/crm/v3/objects/emails/batch/read_read",
                "security": [
                    {
                        "oauth2": [
                            "crm.objects.contacts.read",
                            "sales-email-read"
                        ]
                    }
                ]
            }
        },
        "/batch/update": {
            "post": {
                "tags": [
                    "Batch"
                ],
                "summary": "Update a batch of emails by internal ID, or unique property values",
                "description": "Update a batch of emails using their internal IDs or unique property values.",
                "operationId": "post-/crm/v3/objects/emails/batch/update_update",
                "security": [
                    {
                        "oauth2": [
                            "crm.objects.contacts.write",
                            "sales-email-read"
                        ]
                    }
                ]
            }
        },
        "/batch/upsert": {
            "post": {
                "tags": [
                    "Batch"
                ],
                "summary": "Create or update a batch of emails by unique property values",
                "description": "Create or update records identified by a unique property value as specified by the `idProperty` query param. `idProperty` query param refers to a property whose values are unique for the object.",
                "operationId": "post-/crm/v3/objects/emails/batch/upsert_upsert",
                "security": [
                    {
                        "oauth2": [
                            "crm.objects.contacts.write",
                            "sales-email-read"
                        ]
                    }
                ]
            }
        },
        "/search": {
            "post": {
                "tags": [
                    "Search"
                ],
                "summary": "Search for emails using specified criteria and filters.",
                "description": "Perform a search for emails based on the provided query parameters and return matching results.",
                "operationId": "post-/crm/v3/objects/emails/search_doSearch",
                "security": [
                    {
                        "oauth2": [
                            "crm.objects.contacts.read",
                            "sales-email-read"
                        ]
                    }
                ],
                "x-hubspot-rate-limit-exemptions": [
                    "ten-secondly"
                ]
            }
        },
        "/{emailId}": {
            "get": {
                "tags": [
                    "Basic"
                ],
                "summary": "Read",
                "description": "Read an Object identified by `{emailId}`. `{emailId}` refers to the internal object ID by default, or optionally any unique property value as specified by the `idProperty` query param.  Control what is returned via the `properties` query param.",
                "operationId": "get-/crm/v3/objects/emails/{emailId}_getById",
                "security": [
                    {
                        "oauth2": [
                            "crm.objects.contacts.read",
                            "sales-email-read"
                        ]
                    }
                ]
            },
            "delete": {
                "tags": [
                    "Basic"
                ],
                "summary": "Archive",
                "description": "Move an Object identified by `{emailId}` to the recycling bin.",
                "operationId": "delete-/crm/v3/objects/emails/{emailId}_archive",
                "security": [
                    {
                        "oauth2": [
                            "crm.objects.contacts.write",
                            "sales-email-read"
                        ]
                    }
                ]
            },
            "patch": {
                "tags": [
                    "Basic"
                ],
                "summary": "Update",
                "description": "Perform a partial update of an Object identified by `{emailId}`or optionally a unique property value as specified by the `idProperty` query param. `{emailId}` refers to the internal object ID by default, and the `idProperty` query param refers to a property whose values are unique for the object. Provided property values will be overwritten. Read-only and non-existent properties will result in an error. Properties values can be cleared by passing an empty string."[...]",
                "operationId": "patch-/crm/v3/objects/emails/{emailId}_update",
                "security": [
                    {
                        "oauth2": [
                            "crm.objects.contacts.write",
                            "sales-email-read"
                        ]
                    }
                ]
            }
        }
    },
    "components": {
        "securitySchemes": {
            "developer_hapikey": {
                "type": "apiKey",
                "name": "hapikey",
                "in": "query"
            },
            "hapikey": {
                "type": "apiKey",
                "name": "hapikey",
                "in": "query"
            },
            "oauth2": {
                "type": "oauth2",
                "flows": {
                    "authorizationCode": {
                        "authorizationUrl": "https://app.hubspot.com/oauth/authorize",
                        "tokenUrl": "https://api.hubapi.com/oauth/v1/token",
                        "scopes": {
                            "crm-public-object-api-access": "",
                            "crm.objects.contacts.read": "",
                            "crm.objects.contacts.write": "",
                            "oauth": "",
                            "oauth-access": "",
                            "sales-email-read": ""
                        }
                    }
                }
            },
            "private_apps": {
                "type": "apiKey",
                "name": "private-app",
                "in": "header",
                "x-ballerina-name": "privateApp"
            },
            "private_apps_legacy": {
                "type": "apiKey",
                "name": "private-app-legacy",
                "in": "header",
                "x-ballerina-name": "privateAppLegacy"
            }
        }
    },
    "x-hubspot-available-client-libraries": [
        "Node",
        "Python",
        "Ruby",
        "PHP"
    ],
    "x-hubspot-product-tier-requirements": {
        "marketing": "FREE",
        "sales": "FREE",
        "service": "FREE",
        "cms": "FREE",
        "commerce": "FREE",
        "crmHub": "FREE",
        "dataHub": "FREE"
    }
}